import { Professional } from "./professional";

export interface Project {
    featured: boolean;
    id?: string; // Optional because it will be generated by the backend
    name: string;
    type: string;
    location: string;
    year: string;
    description: string;
    images: string[];
    pid: string; // PID of the associated Professional
}

export interface ProjectWithProfessional extends Project {
	professional?: Professional;
}