import { Package } from "@concolabs-dev/payment";

export const SUPPLIER_PACKAGE: Package[] = [
	{
		title: "User Monthly",
		price: "LKR 3,000",
		features: [],
		priceId: process.env.NEXT_PUBLIC_PRICE_ID_SUPPLIER_BASIC || "",
		highlighted: false,
		packageName: "BML_SUP_BASIC",
	},
	// {
	//   title: "Gold User",
	//   price: "LKR 10,000",
	//   features: [],
	//   highlighted: false,
	//   priceId: "price_1SEsFYHb6l5GodkUuXISMv2N",
	//   packageName: "BML_GOLD",
	// },
	{
		title: "Year at Once",
		price: "LKR 30,000",
		features: [],
		highlighted: false,
		priceId: process.env.NEXT_PUBLIC_PRICE_ID_SUPPLIER_ANNUAL || "",
		packageName: "BML_SUP_ANUAL",
	},
] as const;

export const PROFESSIONAL_PACKAGE: Package[] = [
	{
		title: "User Monthly",
		price: "LKR 3,000",
		features: [],
		priceId: process.env.NEXT_PUBLIC_PRICE_ID_PROFESSIONAL_BASIC || "",
		highlighted: false,
		packageName: "BML_PRF_BASIC",
	},
	// {
	//   title: "Gold User",
	//   price: "LKR 10,000",
	//   features: [],
	//   highlighted: false,
	//   priceId: "price_1SEsFYHb6l5GodkUuXISMv2N",
	//   packageName: "BML_GOLD",
	// },
	{
		title: "Year at Once",
		price: "LKR 30,000",
		features: [],
		highlighted: false,
		priceId: process.env.NEXT_PUBLIC_PRICE_ID_PROFESSIONAL_ANNUAL || "",
		packageName: "BML_PRF_ANUAL",
	},
];

export const PROFESSIONAL_TYPES = [
	"Architect",
	"Contractor",
	"Quantity Surveyor",
	"Interior Designer",
	"Structural Engineer",
] as const;

export const SPECIALTY_OPTIONS = [
	"Residential",
	"Commercial",
	"Industrial",
	"Institutional",
	"Sustainable Design",
	"Urban Planning",
	"Interior Design",
	"Landscape Design",
	"Renovation",
	"High-rise Buildings",
	"Infrastructure",
	"Healthcare",
	"Educational",
	"Hospitality",
	"Mixed-Use Development",
	"Affordable Housing",
	"Luxury Residential",
	"Retail & Shopping Centers",
	"Office Buildings",
	"Warehouses & Logistics",
	"Manufacturing Facilities",
	"Religious Buildings",
	"Sports & Recreation",
	"Transportation Infrastructure",
	"Water & Wastewater Treatment",
	"Power & Energy Projects",
	"Telecommunications Infrastructure",
	"Agricultural Buildings",
	"Government Buildings",
	"Cultural & Heritage Buildings",
	"Resort & Tourism",
	"Residential Complexes",
	"Gated Communities",
	"Condominiums",
	"Villa Projects",
	"Beach & Coastal Properties",
	"Hill Country Properties",
	"Eco-Friendly Construction",
	"Smart Buildings",
	"Prefabricated Construction",
	"Modular Construction",
	"Heritage Restoration",
	"Seismic Design",
	"Tropical Architecture",
	"Green Roofs & Walls",
	"Solar Integration",
	"Rainwater Harvesting",
	"Disaster-Resistant Construction",
	"Low-Cost Housing",
	"Social Housing",
	"Student Housing",
	"Senior Living",
	"Co-working Spaces",
	"Data Centers",
	"Laboratories",
	"Clean Rooms",
	"Cold Storage",
	"Food Processing Facilities",
] as const;

export const SERVICE_OPTIONS = [
	"Architectural Design",
	"Construction Management",
	"Cost Estimation",
	"Interior Design",
	"Landscape Design",
	"Project Management",
	"Structural Engineering",
	"MEP Engineering",
	"Urban Planning",
	"Feasibility Studies",
	"Building Information Modeling (BIM)",
	"Sustainable Design Consulting",
	"Construction Supervision",
	"Cost Management",
	"Dispute Management",
	"Contracts Management",
	"Technical Auditing",
	"Building Surveying",
	"Environmental Impact Assessment",
	"Geotechnical Engineering",
	"Fire Safety Consulting",
	"Energy Auditing",
	"Property Valuation",
	"Building Maintenance",
	"Renovation & Restoration",
	"3D Modeling & Visualization",
	"Permit & Approval Services",
	"Material Testing & Quality Control",
	"Site Investigation",
	"Construction Procurement",
	"Value Engineering",
	"Risk Management",
	"Health & Safety Consulting",
	"Building Code Compliance",
	"LEED Certification Consulting",
	"Demolition Services",
	"Waterproofing Consultation",
	"Acoustics Consulting",
	"Lighting Design",
	"HVAC Design",
	"Plumbing Design",
	"Electrical Design",
	"Security Systems Design",
	"Smart Building Integration",
	"Post-Construction Services",
	"Warranty & Defects Management",
	"Building Performance Analysis",
	"Construction Documentation",
	"As-Built Documentation",
	"Facility Management Consulting",
	"Space Planning",
	"Building Automation Systems",
	"Renewable Energy Systems Design",
	"Solar Panel Installation Design",
	"Green Building Certification",
	"Construction Scheduling",
	"Resource Planning",
	"Subcontractor Management",
] as const;
